#!/usr/bin/env python

import sys
import os

if os.environ.get('LC_CTYPE', '') == 'UTF-8':
    os.environ['LC_CTYPE'] = 'en_US.UTF-8'

from src import terraform_remote_state

def main():
    return terraform_remote_state.main()

if __name__ == '__main__':
    sys.exit(main())
